# 第十一章——期约与异步函数

ES 6 及之后的几个版本逐步加大了对异步编程机制的支持。

- ES 6 新增了 Promise 引用类型，支持优雅地定义和组织异步逻辑。
- 接下来几个版本增加了使用 async 和 await 关键字定义异步函数的机制。

异步日志输出的方式：setTimeout(console.log, 0, …params)，旨在演示执行顺序及其他异步行为。这样可以让期约等返回的值达到其最终状态。此外，浏览器控制台的输出经常能打印出 JS 运行中无法获取的对象信息（比如期约的状态）。

## 异步编程

同步行为和异步行为的对立统一是计算机科学的一个基本概念。在 JS 这种单线程事件循环模型中，同步操作与异步操作更是代码所要依赖的核心机制。异步行为是为了优化因计算量大而时间长的操作。适用于在等待其他操作完成的同时，即使运行其他指令，要求系统也能保持稳定

异步操作并不一定计算量大或要等很长时间。只要不想为等待某个异步操作而阻塞线程执行，就可以使用。

### 同步与异步

同步行为对应内存中顺序执行的处理器指令。每条指令都会严格按照它们出现的顺序来执行，执行后也能立即获得存储在系统本地（如寄存器或系统内存）的信息。这样的执行流程容易分析程序在执行到代码任意位置时的状态（比如变量的值）。例如执行一次简单的数学计算：在程序执行的每一步，都可以推断出程序的状态。因为后面的指令总是在前面的指令完成后才会执行。等到最后一条指定执行完毕，存储在 x 的值就立即可以使用

```js
let x = 3;
x = x + 4;
```

这两行代码对应的低级指令（从 JavaScript 到 x86）：

1. 操作系统在栈内存上分配一个存储浮点数值的空间
2. 针对这个值做一次数学计算，
3. 把计算结果写回之前分配的内存中。

所有这些指令都是在单个线程中按顺序执行的。在低级指令的层面，有充足的工具可以确定系统状态。

而异步行为类似于系统中断，即当前进程外部的实体可以触发代码执行。如果代码要访问一些高延迟的资源，比如向远程服务器发送请求并等待响应，那么就会出现长时间的等待。异步操作的例子可以是在定时回调中执行一次简单的数学计算：

```js
let x = 3;
setTimeout(() => (x = x + 4), 1000);
```

这段程序最终与同步代码执行的任务一样，都是把两个数加在一起，但执行线程不知道 x 值何时会改变，因为这取决于回调何时从消息队列出列并执行。

异步代码不容易推断。第二个指令块（加操作及赋值操作）是由系统计时器触发的，这会生成一个入队执行的中断。到底什么时候会触发 这个中断，这对 JavaScript 运行时来说是一个黑盒，因此实际上无法预知（尽管可以保证这发生在当前 线程的同步代码执行之后，否则回调都没有机会出列被执行）。无论如何，在排定回调以后基本没办法知道系统状态何时变化。

为了让后续代码能够使用 x，异步执行的函数需要在更新 x 的值以后通知其他代码。如果程序不需要这个值，那么就只管继续执行，不必等待这个结果了。

### 以往的异步编程模式

异步行为是 JS 的基础，但早期的实现不理想，只支持定义回调函数来表明异步操作完成。这样的主要问题是：**串联多个异步操作，通常需要深度嵌套的回调函数（俗称“回调地狱”）来解决**

以下是一个异步函数。setTimeout 可以定义一个在指定时间之后会被调度执行的回调函数。1000 毫秒之后，JS 运行时会把回调函数**推到自己的消息队列上去等待执行**。此时回调什么时候出列被执行对代码就完全不可见了。另外，double() 函数在 setTimeout 成功调度异步操作之后会立即退出。

```js
function double(value) {
  setTimeout(() => setTimeout(console.log, 0, value * 2), 1000);
}
double(3);
// 6（大约 1000 毫秒之后）
```

#### 异步返回值

若 setTimeout 操作会返回一个有用的值，则将值传给需要它的地方的主要策略是给异步操作提供一个回调，参数中包含要使用返回值的代码。这里的 setTimeout 调用告诉 JS 运行时在 1000 毫秒之后把一个函数推到消息队列上。这个函数会由运行时负责异步调度执行。而位于函数闭包中的回调及其参数在异步执行时仍然是可用的。

```js
function double(value, callback) {
  setTimeout(() => callback(value * 2), 1000);
}
double(3, (x) => console.log(`I was given: ${x}`));
// I was given: 6（大约 1000 毫秒之后）
```

#### 失败处理

出现了如下的成功回调和失败回调。这种模式已经不可取了，因为必须在初始化异步操作时定义回调。异步函数的返回值只在短时间内存在，只有预备好将这个短时间内存在的值作为参数的回调才能接收到它

```js
function double(value, success, failure) {
  setTimeout(() => {
    try {
      if (typeof value !== "number") {
        throw "Must provide number as first argument";
      }
      success(2 * value);
    } catch (e) {
      failure(e);
    }
  }, 1000);
}

const successCallback = (x) => console.log(`Success: ${x}`);
const failureCallback = (e) => console.log(`Failure: ${e}`);

double(3, successCallback, failureCallback);
double("b", successCallback, failureCallback);
// Success: 6（大约 1000 毫秒之后）
// Failure: Must provide number as first argument（大约 1000 毫秒之后）
```

#### 嵌套异步回调

如果异步返值又依赖另一个异步返回值，这就要求嵌套回调。显然，随着代码越来越复杂，回调策略不具有扩展性。

```js
const successCallback = (x) => {
  double(x, (y) => console.log(`Success: ${y}`));
};
const failureCallback = (e) => console.log(`Failure: ${e}`);
double(3, successCallback, failureCallback);
// Success: 12（大约 1000 毫秒之后）
```

## 期约

期约是对尚不存在结果的一个替身。计算机科学家还使用了“终局”（eventual）、“期许”（future）、“延迟”（delay）和“迟付”（deferred）等术语指代同样的概念，来描述一种异步程序执行的机制。

### Promises/A+规范

- 早期的期约机制在 jQuery 和 Dojo 中是以 Deferred API 的形式出现的。
- 2010 年，CommonJS 项目实现的 Promises/A 规范日益流行起来。Q 和 Bluebird 等第三方 JavaScript 期约库也越来越得到社区认可。
- 为弥合现有实现之间的差异，2012 年 Promises/A+组织分叉（fork）了 CommonJS 的 Promises/A 建议，并制定了 Promises/A+规范。这个规范最终成为了 ECMAScript 6 规范实现的范本。

ECMAScript 6 增加了 Promise 类型，推出后成为了主导性的异步编程机制。所有现代浏览器都支持 ES6 期约，很多其他浏览器 API（如 fetch()和 Battery Status API）也以期约为基础。

### 期约基础

引用类型 Promise 可以通过 new 操作符来实例化。创建时需要传入执行器（executor）函数作为参数，如果不提供执行器函数，就会抛出 SyntaxError。

```js
let p = new Promise(() => {});
setTimeout(console.log, 0, p); // Promise <pending>
```

#### 期约状态机

期约是一个有状态的对象，期约的状态是私有的，不能直接通过 JS 检测到。期约故意将异步行为封装起来，从而隔离外部的同步代码。

- 待定（pending），是最初始状态，可以落定兑现或拒绝状态。**落定是不可逆的**
- 兑现（fulfilled，有时候也称为“解决”，resolved）
- 拒绝（rejected）

> **期约并非必然会脱离待定状态**。`new Promise(() => {})`

#### 解决值、拒绝理由及期约用例

期约主要有两大用途。

1. 抽象地表示一个异步操作。期约的状态代表期约是否完成。有时这个状态机就是最有用的信息。比如，假设期约要向服务器发送一个 HTTP 请求。
   - 请求返回 200~299 范围内的状态码就足以让期约的状态变为“兑现”。
   - 如果请求返回的状态码不在 200~299 这个范围内，那么就会把期约状态切换为“拒绝”。
2. 状态改变时让异步操作生成的值（或被拒绝时拒绝的理由）可以被程序访问。比如，假设期约向服务器发送一个 HTTP 请求并预定会返回一个 JSON
   - 如果请求返回范围在 200~299 的状态码，则足以让期约的状态变为兑现。此时期约内部就可以收到一个 JSON 字符串。
   - 如果请求返回的状态码不在 200~299 这个范围内，那么就会把期约状态切换为拒绝。此时拒绝的理由可能是一个 Error 对象，包含着 HTTP 状态码及相关错误消息。

为了支持这两种用例，每个期约只要状态切换为兑现，就会有一个私有的内部值（value）。状态切换为拒绝，就会有一个私有的内部理由（reason）。两者都是包含原始值或对象的不可修改的引用，都是可选的，默认值为 undefined。在期约到达某个落定状态时执行的异步代码始终会收到这个值或理由。

#### 通过执行函数控制期约状态

期约的状态是私有的，只能在内部进行操作，内部操作在期约的执行器函数中完成。执行器函数的职责：

- 初始化期约的异步行为
- 控制状态的最终转换：通过调用它的两个函数参数实现的。调用 resolve() 会把状态切换为兑现，调用 reject() 会把状态切换为拒绝。另外，调用 reject()也会抛出错误。

```js
let p1 = new Promise((resolve, reject) => resolve());
setTimeout(console.log, 0, p1); // Promise <resolved>
let p2 = new Promise((resolve, reject) => reject());
setTimeout(console.log, 0, p2); // Promise <rejected>
// Uncaught error (in promise)
```

示例中并没有什么异步操作，因初始化期约时，执行器函数已经改变了每个期约的状态。

执行器函数是同步执行的，因为它是期约的初始化程序。

```js
new Promise(() => setTimeout(console.log, 0, "executor"));
setTimeout(console.log, 0, "promise initialized");
// executor
// promise initialized

// 添加 setTimeout 可以推迟切换状态：
let p = new Promise((resolve, reject) => setTimeout(resolve, 1000));
// 在 console.log 打印期约实例的时候，还不会执行超时回调（即 resolve()）
setTimeout(console.log, 0, p); // Promise <pending>
```

一旦 resolve() 和 reject() 之一被调用，状态转换都不可撤销了。于是继续修改状态会静默失败

```js
let p = new Promise((resolve, reject) => {
  resolve();
  reject(); // 没有效果
});
setTimeout(console.log, 0, p); // Promise <resolved>
```

为避免期约卡在待定状态，可以添加一个定时退出功能。比如，可以通过 setTimeout 设置一个 10 秒钟后无论如何都会拒绝期约的回调：

```js
let p = new Promise((resolve, reject) => {
  setTimeout(reject, 10000); // 10 秒后调用 reject()
  // 执行函数的逻辑
});
setTimeout(console.log, 0, p); // Promise <pending>
setTimeout(console.log, 11000, p); // 11 秒后再检查状态
// (After 10 seconds) Uncaught error
// (After 11 seconds) Promise <rejected>
```

因为期约的状态只能改变一次，所以这里的超时拒绝逻辑中可以放心地设置让期约处于待定状态的最长时间。如果执行器中的代码在超时之前已经解决或拒绝，那么超时回调再尝试拒绝也会静默失败。

#### promise.resolve()

期约不必一开始就处于待定状态，再通过执行器函数转换为落定状态。

Promise.resolve() 静态方法可以**实例化一个解决的期约**，第一个参数是期约解决的值。这个方法可以把任何值都转换为一个期约，它可以说是一个幂等方法，这个幂等性会保留传入期约的状态

```js
let p1 = new Promise((resolve, reject) => resolve());
let p2 = Promise.resolve();

setTimeout(console.log, 0, Promise.resolve(4, 5, 6));
// Promise <resolved>: 4 // 多余的参数会忽略

setTimeout(console.log, 0, p1 === Promise.resolve(p1));
// true

setTimeout(console.log, 0, p1); // Promise <pending>
setTimeout(console.log, 0, Promise.resolve(p1)); // Promise <pending>
setTimeout(console.log, 0, p1 === Promise.resolve(p1)); // true
```

注意，这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约。因此，也可能导致不符合预期的行为：

```js
let p = Promise.resolve(new Error("foo"));
setTimeout(console.log, 0, p);
// Promise <resolved>: Error: foo
```

#### PROMISE.REJECT()

Promise.reject() 会实例化一个拒绝的期约并抛出一个异步错误（这个错误不能通过 try/catch 捕获，而只能通过拒绝处理程序捕获）。第一个参数是拒绝的期约的理由，这个参数也会传给后续的拒绝处理程序：

```js
let p1 = new Promise((resolve, reject) => reject());
let p2 = Promise.reject();

let p = Promise.reject(3);
setTimeout(console.log, 0, p); // Promise <rejected>: 3
p.then(null, (e) => setTimeout(console.log, 0, e)); // 3
```

Promise.reject() 并没有照搬 Promise.resolve()的幂等逻辑。如果给它传一个期约对象，则期约会成为它返回的拒绝期约的理由

```js
setTimeout(console.log, 0, Promise.reject(Promise.resolve()));
// Promise <rejected>: Promise <resolved>
```

#### 同步/异步执行的二元性

Promise 的设计很大程度上会导致一种完全不同于 JS 的计算模式。其中包含了两种模式下抛出错误的情形：

```js
try {
  throw new Error("foo");
} catch (e) {
  console.log(e);
  // Error: foo //捕获了错误
}
try {
  Promise.reject(new Error("bar"));
} catch (e) {
  console.log(e);
}
// Uncaught (in promise) Error: bar //没有捕获到
```

这里的同步代码之所以没有捕获期约抛出的错误，是因为它没有通过异步模式捕获错误。从这里就可以看出期约真正的异步特性：它们是同步对象（在同步执行模式中使用），但也是异步执行模式的媒介。拒绝期约的错误并没有抛到执行同步代码的线程里，而是通过浏览器异步消息队列来处理的。因此，try/catch 块并不能捕获该错误。

代码一旦开始以异步模式执行，则唯一与之交互的方式就是使用异步结构——期约的方法。

### 期约的实例方法

期约实例的方法是连接外部同步代码与内部异步代码之间的桥梁。可以访问异步操作返回的数据，处理期约成功和失败的结果，连续对期约求值，或者添加只有期约进入终止状态时才会执行的代码。

#### 实现 THENABLE 接口

在 ECMAScript 暴露的异步结构中，任何对象都有一个 then()方法，被认为实现了 Thenable 接口。Promise 类型实现了 Thenable 接口。

```js
class MyThenable {
  //实现这一接口的最简单的类
  then() {}
}
```

#### PROMISE.PROTOTYPE.THEN()

Promise.prototype.then() 是为期约实例添加处理程序的主要方法。 then()方法接收最多 两个参数：onResolved 处理程序和 onRejected 处理程序。两个参数都是可选的，如果提供的话， 则会在期约分别进入“兑现”和“拒绝”状态时执行，这两个操作一定是互斥的。方法返回一个新的期约实例：

```js
function onResolved(id) {
  setTimeout(console.log, 0, id, "resolved");
}
function onRejected(id) {
  setTimeout(console.log, 0, id, "rejected");
}
let p1 = new Promise((resolve, reject) => setTimeout(resolve, 3000));
let p2 = new Promise((resolve, reject) => setTimeout(reject, 3000));

p1.then(
  () => onResolved("p1"),
  () => onRejected("p1")
);
p2.then(
  () => onResolved("p2"),
  () => onRejected("p2")
);

//（3 秒后）
// p1 resolved
// p2 rejected
```

传给 then() 的非函数类型的参数都会被静默忽略。如果想只提供 onRejected 参数，则第一个参数传 undefined。这有助于避免在内存中创建多余的对象

```js
function onResolved(id) {
  setTimeout(console.log, 0, id, "resolved");
}
function onRejected(id) {
  setTimeout(console.log, 0, id, "rejected");
}
let p1 = new Promise((resolve, reject) => setTimeout(resolve, 3000));
let p2 = new Promise((resolve, reject) => setTimeout(reject, 3000));

p1.then("gobbeltygook"); // 非函数处理程序会被静默忽略
p2.then(null, () => onRejected("p2")); // 不传 onResolved 处理程序的规范写法

// p2 rejected（3 秒后）
let p1 = new Promise(() => {});
let p2 = p1.then();
setTimeout(console.log, 0, p1); // Promise <pending>
setTimeout(console.log, 0, p2); // Promise <pending>
setTimeout(console.log, 0, p1 === p2); // false
```

这个新期约实例基于 onResovled 处理程序的返回值构建。即该处理程序的返回值会通过 Promise.resolve()包装来生成新期约。如果没有提供这个处理程序，则 Promise.resolve()就会 包装上一个期约解决之后的值。如果没有显式的返回语句，则 Promise.resolve()会包装默认的返回 值 undefined。

```js
let p1 = Promise.resolve("foo");
// 若调用 then()时不传处理程序，则原样向后传
let p2 = p1.then();
setTimeout(console.log, 0, p2); // Promise <resolved>: foo
// 这些都一样
let p3 = p1.then(() => undefined);
let p4 = p1.then(() => {});
let p5 = p1.then(() => Promise.resolve());
setTimeout(console.log, 0, p3); // Promise <resolved>: undefined
setTimeout(console.log, 0, p4); // Promise <resolved>: undefined
setTimeout(console.log, 0, p5); // Promise <resolved>: undefined
```

如果有显式的返回值，则 Promise.resolve()会包装这个值：

```js
// 这些都一样
let p6 = p1.then(() => "bar");
let p7 = p1.then(() => Promise.resolve("bar"));

setTimeout(console.log, 0, p6); // Promise <resolved>: bar
setTimeout(console.log, 0, p7); // Promise <resolved>: bar

let p8 = p1.then(() => new Promise(() => {}));
let p9 = p1.then(() => Promise.reject());
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p8); // Promise <pending>
setTimeout(console.log, 0, p9); // Promise <rejected>: undefined
```

抛出异常会返回拒绝的期约，返回错误值不会触发上面的拒绝行为，而会把错误对象包装在一个解决的期约中：

```js
let p10 = p1.then(() => {
  throw "baz";
}); // Uncaught (in promise) baz
setTimeout(console.log, 0, p10); // Promise <rejected> baz

let p11 = p1.then(() => Error("qux"));
setTimeout(console.log, 0, p11); // Promise <resolved>: Error: qux
```

onRejected 处理程序也与之类似：onRejected 处理程序返回的值也会被 Promise.resolve()包装。但是想一想，onRejected 处理程序的任务不就是捕获异步错误吗？因此，拒绝处理程序在捕获错误后不抛出异常是符合期约的行为，应该返回一个解决期约。

下面的代码片段展示了用 Promise.reject()替代之前例子中的 Promise.resolve()之后的 结果：

```js
let p1 = Promise.reject("foo");
// 调用 then()时不传处理程序则原样向后传
let p2 = p1.then();
// Uncaught (in promise) foo
setTimeout(console.log, 0, p2); // Promise <rejected>: foo
// 这些都一样
let p3 = p1.then(null, () => undefined);
let p4 = p1.then(null, () => {});
let p5 = p1.then(null, () => Promise.resolve());
setTimeout(console.log, 0, p3); // Promise <resolved>: undefined
setTimeout(console.log, 0, p4); // Promise <resolved>: undefined
setTimeout(console.log, 0, p5); // Promise <resolved>: undefined
// 这些都一样
let p6 = p1.then(null, () => "bar");
let p7 = p1.then(null, () => Promise.resolve("bar"));
setTimeout(console.log, 0, p6); // Promise <resolved>: bar
setTimeout(console.log, 0, p7); // Promise <resolved>: bar
// Promise.resolve()保留返回的期约
let p8 = p1.then(null, () => new Promise(() => {}));
let p9 = p1.then(null, () => Promise.reject());
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p8); // Promise <pending>
setTimeout(console.log, 0, p9); // Promise <rejected>: undefined
let p10 = p1.then(null, () => {
  throw "baz";
});
// Uncaught (in promise) baz
setTimeout(console.log, 0, p10); // Promise <rejected>: baz
let p11 = p1.then(null, () => Error("qux"));
setTimeout(console.log, 0, p11); // Promise <resolved>: Error: qux
```

#### PROMISE.PROTOTYPE.CATCH()

Promise.prototype.catch() 方法用于给期约添加拒绝处理程序。接收的参数为 onRejected 处理程序，返回一个新的期约实例。事实上是一个语法糖，调用它就相当于调用 Promise.prototype.then(null, onRejected)。

```js
let p = Promise.reject();
let onRejected = function (e) {
  setTimeout(console.log, 0, "rejected");
};
// 这两种添加拒绝处理程序的方式是一样的：
p.then(null, onRejected); // rejected
p.catch(onRejected); // rejected

let p1 = new Promise(() => {});
let p2 = p1.catch();

setTimeout(console.log, 0, p1); // Promise <pending>
setTimeout(console.log, 0, p2); // Promise <pending>
setTimeout(console.log, 0, p1 === p2); // false
```

#### PROMISE.PROTOTYPE.FINALLY()

Promise.prototype.finally() 方法用于给期约添加 onFinally 处理程序，在期约转换为解决或拒绝状态时都会执行。返回一个新的期约实例。这个新期约实例不同于 then()或 catch()方式返回的实例。因为 onFinally 被设计为一个状态无关的方法，所以在大多数情况下它将表现为父期约的传递。对于已解决状态和被拒绝状态都是如此。

这个方法可以避免 onResolved 和 onRejected 处理程序中出现冗余代码。但 onFinally 处理程序没有办法知道期约的状态是解决还是拒绝，所以这个方法主要用于添加清理代码。

```js
let p1 = Promise.resolve();
let p2 = Promise.reject();

let onFinally = function () {
  setTimeout(console.log, 0, "Finally!");
};

p1.finally(onFinally); // Finally
p2.finally(onFinally); // Finally

let p = new Promise(() => {});
let newP = p.finally();
setTimeout(console.log, 0, p); // Promise <pending>
setTimeout(console.log, 0, newP); // Promise <pending>
setTimeout(console.log, 0, p === newP); // false
let p1 = Promise.resolve("foo");
// 这里都会原样后传
let p2 = p1.finally();
let p3 = p1.finally(() => undefined);
let p4 = p1.finally(() => {});
let p5 = p1.finally(() => Promise.resolve());
let p6 = p1.finally(() => "bar");
let p7 = p1.finally(() => Promise.resolve("bar"));
let p8 = p1.finally(() => Error("qux"));
setTimeout(console.log, 0, p2); // Promise <resolved>: foo
setTimeout(console.log, 0, p3); // Promise <resolved>: foo
setTimeout(console.log, 0, p4); // Promise <resolved>: foo
setTimeout(console.log, 0, p5); // Promise <resolved>: foo
setTimeout(console.log, 0, p6); // Promise <resolved>: foo
setTimeout(console.log, 0, p7); // Promise <resolved>: foo
setTimeout(console.log, 0, p8); // Promise <resolved>: foo
```

如果返回的是一个待定的期约，或者 onFinally 处理程序抛出了错误（显式抛出或返回了一个拒绝期约），则会返回相应的期约（待定或拒绝）

```js
// Promise.resolve()保留返回的期约
let p9 = p1.finally(() => new Promise(() => {}));
let p10 = p1.finally(() => Promise.reject());
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p9); // Promise <pending>
setTimeout(console.log, 0, p10); // Promise <rejected>: undefined
let p11 = p1.finally(() => {
  throw "baz";
});
// Uncaught (in promise) baz
setTimeout(console.log, 0, p11); // Promise <rejected>: baz
```

返回待定期约的情形并不常见，因为只要期约一解决，新期约仍然会原样后传初始的期约：

```js
let p1 = Promise.resolve("foo");
// 忽略解决的值
let p2 = p1.finally(
  () => new Promise((resolve, reject) => setTimeout(() => resolve("bar"), 100))
);
setTimeout(console.log, 0, p2); // Promise <pending>
setTimeout(() => setTimeout(console.log, 0, p2), 200);
// 200 毫秒后：
// Promise <resolved>: foo
```

#### 非重入期约方法

当期约进入落定状态时，与该状态相关的处理程序仅会被排期，而非立即执行。跟在添加处理程序的代码之后的同步代码会先执行。即使期约一开始就是与附加处理程序关联的状态（先添加处理程序后解决期约也是一样的）。这个特性由 JS 运行时保证，被称为“非重入”（non-reentrancy）特性。非重入适用于 onResolved/onRejected 处理程序、catch()处理程序和 finally()处理程序。

```js
let p1 = Promise.resolve();
p1.then(() => console.log("p1.then() onResolved"));
console.log("p1.then() returns");

let p2 = Promise.reject();
p2.then(null, () => console.log("p2.then() onRejected"));
console.log("p2.then() returns");

let p3 = Promise.reject();
p3.catch(() => console.log("p3.catch() onRejected"));
console.log("p3.catch() returns");

let p4 = Promise.resolve();
p4.finally(() => console.log("p4.finally() onFinally"));
console.log("p4.finally() returns");

// p1.then() returns
// p2.then() returns
// p3.catch() returns
// p4.finally() returns
// p1.then() onResolved
// p2.then() onRejected
// p3.catch() onRejected
// p4.finally() onFinally
```

如果添加处理程序后，同步代码才改变期约状态，那么处理程序仍然会基于该状态变化表现出非重入特性。即使先添加了 onResolved 处理程序，再同步调用 resolve()，处理程序也不会进入同步线程执行。

```js
let synchronousResolve;
// 创建一个期约并将解决函数保存在一个局部变量中
let p = new Promise((resolve) => {
  synchronousResolve = function () {
    console.log("1: invoking resolve()");
    resolve();
    console.log("2: resolve() returns");
  };
});

p.then(() => console.log("4: then() handler executes")); //先添加处理程序
synchronousResolve(); //同步调用 resolve()
console.log("3: synchronousResolve() returns");

// 实际的输出：
// 1: invoking resolve()
// 2: resolve() returns
// 3: synchronousResolve() returns
// 4: then() handler executes //处理程序也会等到运行的消息队列让它出列时才会执行
```

#### 邻近处理程序的执行顺序

如果给期约添加了多个处理程序，当期约状态变化时，相关处理程序会按照添加它们的顺序依次执行。无论是 then()、catch()还是 finally()添加的处理程序都是如此。

```js
let p1 = Promise.resolve();
let p2 = Promise.reject();
p1.then(() => setTimeout(console.log, 0, 1));
p1.then(() => setTimeout(console.log, 0, 2));
// 1
// 2
```

#### 传递解决值和拒绝理由

到了落定状态后，期约会提供其解决值（如果兑现）或其拒绝理由（如果拒绝）给相关状态的处理程序。在执行函数中，解决的值和拒绝的理由分别作为 resolve() 和 reject() 的第一个参数。然后，这些值又会传给它们各自的处理程序，作为 onResolved 或 onRejected 处理程序的唯一参数。Promise.resolve() 和 Promise.reject() 在被调用时就会接收解决值和拒绝理由。

```js
let p1 = new Promise((resolve, reject) => resolve("foo"));
p1.then((value) => console.log(value)); // foo

let p2 = new Promise((resolve, reject) => reject("bar"));
p2.catch((reason) => console.log(reason)); // bar

let p1 = Promise.resolve("foo");
p1.then((value) => console.log(value)); // foo
let p2 = Promise.reject("bar");
p2.catch((reason) => console.log(reason)); // bar
```

#### 拒绝期约与拒绝错误处理

拒绝期约类似于 throw() 表达式，它们都代表需要中断或者特殊处理。在期约的**执行函数或处理程序中**抛出错误会导致拒绝，对应的错误对象会成为拒绝的理由。

```js
let p1 = new Promise((resolve, reject) => reject(Error("foo")));
let p2 = new Promise((resolve, reject) => {
  throw Error("foo");
});
let p3 = Promise.resolve().then(() => {
  throw Error("foo");
});
let p4 = Promise.reject(Error("foo"));
setTimeout(console.log, 0, p1); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p2); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p3); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p4); // Promise <rejected>: Error: foo
// 也会抛出 4 个未捕获错误
```

期约可以以任何理由拒绝，包括 undefined，但最好统一使用错误对象。主要的好处是错误对象可以让浏览器捕获错误对象中的栈追踪信息，对调试是非常关键。例如，前面例子中抛出的 4 个错误的栈追踪信息如下：

```js
// Uncaught (in promise) Error: foo
//  at Promise (test.html:5)
//  at new Promise (<anonymous>)
//  at test.html:5
// Uncaught (in promise) Error: foo
//  at Promise (test.html:6)
//  at new Promise (<anonymous>)
//  at test.html:6
// Uncaught (in promise) Error: foo
//  at test.html:8
// Uncaught (in promise) Error: foo
//  at Promise.resolve.then (test.html:7)
```

所有错误都是异步抛出且未处理的，通过错误对象捕获的栈追踪信息展示了错误发生的路径。注意 Promise.resolve().then() 的错误最后才出现，因为它需要在运行时消息队列中添加处理程序；也就是说，在最终抛出未捕获错误之前它还会创建另一个期约。

异步错误有意思的副作用：在期约中抛出错误时，因为错误实际上是从消息队列中异步抛出的，所以并不会阻止运行时继续执行同步指令：

```js
throw Error("foo");
console.log("bar"); // 这一行不会执行
// Uncaught Error: foo

Promise.reject(Error("foo"));
console.log("bar");
// bar
// Uncaught (in promise) Error: foo
```

异步错误只能通过异步的 onRejected 处理程序捕获，但在解决或拒绝期约之前，执行函数中的错误可以使用 try/catch 在执行函数中捕获错误。

```js
// 正确
Promise.reject(Error("foo")).catch((e) => {});
// 不正确
try {
  Promise.reject(Error("foo"));
} catch (e) {}

let p = new Promise((resolve, reject) => {
  try {
    throw Error("foo");
  } catch (e) {}
  resolve("bar");
});

setTimeout(console.log, 0, p); // Promise <resolved>: bar
```

then() 和 catch() 的 onRejected 处理程序在语义上相当于 try/catch。出发点都是捕获错误之后将其隔离，同时不影响正常逻辑执行。为此，onRejected 处理程序的任务应该是在捕获异步错误之后返回一个解决的期约。

```js
new Promise((resolve, reject) => {
  console.log("begin asynchronous execution");
  reject(Error("bar"));
})
  .catch((e) => {
    //捕获异步错误之后返回了一个解决的期约
    console.log("caught error", e);
  })
  .then(() => {
    console.log("continue asynchronous execution");
  });
// begin asynchronous execution
// caught error Error: bar
// continue asynchronous execution
```

### 期约连锁与期约合成

多个期约组合在一起可以构成强大的代码逻辑。

- 期约连锁：一个期约接一个期约地拼接
- 期约合成：将多个期约组合为一个期约

#### 期约连锁

每个期约实例的方法都会返回一个新的期约对象，新期约又有自己的实例方法。连缀方法调用就可以构成所谓的“期约连锁”。要执行异步任务，可以让每个执行器都返回一个期约实例。这样每个后续期约都会等待之前的期约，也就是**串行化异步任务**。

```js
let p1 = new Promise((resolve, reject) => {
  console.log("p1 executor");
  setTimeout(resolve, 1000);
});

p1.then(
  () =>
    new Promise((resolve, reject) => {
      console.log("p2 executor");
      setTimeout(resolve, 1000);
    })
).then(
  () =>
    new Promise((resolve, reject) => {
      console.log("p3 executor");
      setTimeout(resolve, 1000);
    })
);
// p1 executor（1 秒后）
// p2 executor（2 秒后）
// p3 executor（3 秒后）
```

可以把生成期约的代码提取到一个工厂函数中

```js
function delayedResolve(str) {
  return new Promise((resolve, reject) => {
    console.log(str);
    setTimeout(resolve, 1000);
  });
}

delayedResolve("p1 executor")
  .then(() => delayedResolve("p2 executor"))
  .then(() => delayedResolve("p3 executor"))
  .then(() => delayedResolve("p4 executor"));
```

这种结构可以简洁地将异步任务串行化，解决之前依赖回调的难题

```js
function delayedExecute(str, callback = null) {
  setTimeout(() => {
    console.log(str);
    callback && callback();
  }, 1000);
}
delayedExecute("p1 callback", () => {
  delayedExecute("p2 callback", () => {
    delayedExecute("p3 callback", () => {
      delayedExecute("p4 callback");
    });
  });
});
```

#### 期约图

所以期约连锁可以构建有向非循环图的结构。每个期约都是图中的一个节点，添加的处理程序则是有向顶点。图的方向就是期约的解决或拒绝顺序。

下面的例子展示了一种期约有向图，也就是二叉树：期约的处理程序是按照它们添加的顺序执行的，构成了层序遍历。

```js
//    A
//   / \
//  B   C
// /\   /\
//D  E  F  G

let A = new Promise((resolve, reject) => {
  console.log("A");
  resolve();
});

let B = A.then(() => console.log("B"));
let C = A.then(() => console.log("C"));

B.then(() => console.log("D"));
B.then(() => console.log("E"));
C.then(() => console.log("F"));
C.then(() => console.log("G"));
```

#### Promise.all()和 Promise.race()

Promise 类提供两个将多个期约实例组合成一个期约的静态方法。

- Promise.all()：接收一个可迭代对象，返回一个新期约，会在一组期约全部解决之后再解决。解决值就是所有包含期约解决值的数组，按照迭代器顺序：

```js
let p1 = Promise.all([3, 4]); // 可迭代对象中的元素会通过 Promise.resolve() 转换为期约
let p2 = Promise.all([]); // 空的可迭代对象等价于 Promise.resolve()
let p4 = Promise.all(); // TypeError: cannot read Symbol.iterator of undefined // 无效的语法

let p = Promise.all([
  Promise.resolve(),
  new Promise((resolve, reject) => setTimeout(resolve, 1000)),
]);
setTimeout(console.log, 0, p); // Promise <pending>
p.then(() => setTimeout(console.log, 0, "all() resolved!"));
// all() resolved!（大约 1 秒后）
```

若有一个包含的期约待定，则合成的期约也会待定。

```js
// 永远待定
let p1 = Promise.all([new Promise(() => {})]);
setTimeout(console.log, 0, p1); // Promise <pending>
```

若有一个包含的期约拒绝，则合成的期约拒绝

```js
let p2 = Promise.all([Promise.resolve(), Promise.reject(), Promise.resolve()]);

setTimeout(console.log, 0, p2); // Promise <rejected>
// Uncaught (in promise) undefined
```

如果有期约拒绝，则合成期约的拒绝理由为第一个拒绝的期约的理由。合成的期约会静默处理所有包含期约的拒绝操作

```js
// 第二个期约的拒绝也会被静默处理，不会有错误跑掉
let p = Promise.all([
  Promise.reject(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
]);
p.catch((reason) => setTimeout(console.log, 0, reason)); // 3
// 没有未处理的错误
```

- Promise.race()

Promise.race() 接收一个可迭代对象，返回一个新期约，是一组集合中最先**解决或拒绝**的期约的镜像。

```js
let p1 = Promise.race([
  Promise.resolve(3), // 解决先发生，超时后的拒绝被忽略
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
]);
setTimeout(console.log, 0, p1); // Promise <resolved>: 3

let p2 = Promise.race([
  Promise.reject(4), // 拒绝先发生，超时后的解决被忽略
  new Promise((resolve, reject) => setTimeout(resolve, 1000)),
]);
setTimeout(console.log, 0, p2); // Promise <rejected>: 4

let p3 = Promise.race([
  Promise.resolve(5),
  Promise.resolve(6),
  Promise.resolve(7),
  // 迭代顺序决定了落定顺序
]);
setTimeout(console.log, 0, p3); // Promise <resolved>: 5
```

#### 串行期约合成

基于后续期约使用之前期约的返回值来串联期约是期约的基本功能。这很像函数合成，即将多个函数合成为一个函数。期约也可以像这样合成起来，渐进地消费一个值，并返回一个结果：

```js
function addTwo(x) {
  return x + 2;
}
function addThree(x) {
  return x + 3;
}
function addFive(x) {
  return x + 5;
}
function addTen(x) {
  return Promise.resolve(x).then(addTwo).then(addThree).then(addFive);
}
addTen(8).then(console.log); // 18
```

使用 Array.prototype.reduce()可以写成更简洁的形式：

```js
function addTen(x) {
  return [addTwo, addThree, addFive].reduce(
    (promise, fn) => promise.then(fn),
    Promise.resolve(x)
  );
}
addTen(8).then(console.log); // 18
```

这种模式可以提炼出一个通用函数，可以把任意多个函数作为处理程序合成一个连续传值的期约连 锁。

```js
function compose(...fns) {
  return (x) =>
    fns.reduce((promise, fn) => promise.then(fn), Promise.resolve(x));
}
let addTen = compose(addTwo, addThree, addFive);
```

### 期约扩展

很多第三方期约库实现中具备而 ES 规范却未涉及的特性。

#### 期约取消

某些第三方库，比如 Bluebird，提供了这个特性。

可以在现有实现基础上提供一种临时性的封装，以实现取消期约的功能。这可以用到 “取消令牌”（cancel token）。生成的令牌实例提供了一个接口，利用这个接口可以取消期 约；同时也提供了一个期约的实例，可以用来触发取消后的操作并求值取消状态。

```js
class CancelToken {
  constructor(cancelFn) {
    this.promise = new Promise((resolve, reject) => {
      cancelFn(resolve);
    });
  }
}
```

这个类包装了一个期约，把解决方法暴露给了 cancelFn 参数。这样，外部代码就可以向构造函数 中传入一个函数，从而控制什么情况下可以取消期约。这里期约是令牌类的公共成员，因此可以给它添 加处理程序以取消期约。

```html
<button id="start">Start</button>
<button id="cancel">Cancel</button>

<script>
  class CancelToken {
    constructor(cancelFn) {
      this.promise = new Promise((resolve, reject) => {
        cancelFn(() => {
          setTimeout(console.log, 0, "delay cancelled");
          resolve();
        });
      });
    }
  }
  const startButton = document.querySelector("#start");
  const cancelButton = document.querySelector("#cancel");

  function cancellableDelayedResolve(delay) {
    setTimeout(console.log, 0, "set delay");
    return new Promise((resolve, reject) => {
      const id = setTimeout(() => {
        setTimeout(console.log, 0, "delayed resolve");
        resolve();
      }, delay);
      const cancelToken = new CancelToken((cancelCallback) =>
        cancelButton.addEventListener("click", cancelCallback)
      );
      cancelToken.promise.then(() => clearTimeout(id));
    });
  }
  startButton.addEventListener("click", () => cancellableDelayedResolve(1000));
</script>
```

## 异步函数

async/await 是 ES8 规范新增的。这个特性从行为和语法上都增强了 JavaScript，让以同步方式写的代码 能够异步执行。

```js
let p = new Promise((resolve, reject) => setTimeout(resolve, 1000, 3));
p.then((x) => console.log(x)); // 3

// 其他代码要在这个值可用时访问它，则需要写一个解决处理程序。而这样其他代码都必须塞到期约处理程序中。
```

可以把处理程序定义为一个函数：

```js
function handler(x) {
  console.log(x);
}
let p = new Promise((resolve, reject) => setTimeout(resolve, 1000, 3));
p.then(handler); // 3
```

这个改进其实也不大。这是因为任何需要访问这个期约所产生值的代码，都需要以处理程序的形式 来接收这个值。也就是说，代码照样还是要放到处理程序里。ES8 为此提供了 async/await 关键字。

### 异步函数

async/await 旨在解决利用异步结构组织代码的问题。

#### ASYNC

async 关键字用于声明异步函数。这个关键字可以用在函数声明、函数表达式、箭头函数和方法上：

```js
async function foo() {}
let bar = async function () {};
let baz = async () => {};
class Qux {
  async qux() {}
}
```

使用 async 关键字可以让函数具有异步特征，但总体上其代码仍然是同步求值的。而在参数或闭 包方面，异步函数仍然具有普通 JS 函数的正常行为。

```js
async function foo() {
  console.log(1);
}

foo(); //foo()函数仍然会在后面的指令之前被求值：
console.log(2);
// 1
// 2
```

不过，异步函数如的返回值会被 Promise.resolve()包装成一个期约对象。在函数外部调用这个函数可以得到它返回的期约：

```js
async function foo() {
  console.log(1);
  return 3;
}
// 给返回的期约添加一个解决处理程序
foo().then(console.log);
console.log(2);
// 1
// 2
// 3
```

异步函数的返回值期待（但实际上并不要求）一个实现 thenable 接口的对象，但常规的值也可以。 如果返回的是实现 thenable 接口的对象，则这个对象可以由提供给 then()的处理程序“解包”。如果 不是，则返回值就被当作已经解决的期约。

```js
// 返回一个没有实现 thenable 接口的对象
async function bar() {
  return ["bar"];
}
bar().then(console.log);
// ['bar']
// 返回一个实现了 thenable 接口的非期约对象
async function baz() {
  const thenable = {
    then(callback) {
      callback("baz");
    },
  };
  return thenable;
}
baz().then(console.log);
// baz
```

与在期约处理程序中一样，在异步函数中抛出错误会返回拒绝的期约：

```js
async function foo() {
  console.log(1);
  throw 3;
}
// 给返回的期约添加一个拒绝处理程序
foo().catch(console.log);
console.log(2);
// 1
// 2
// 3
```

不过，拒绝期约的错误不会被异步函数捕获：

```js
async function foo() {
  console.log(1);
  Promise.reject(3);
}
// Attach a rejected handler to the returned promise
foo().catch(console.log);
console.log(2);
// 1
// 2
// Uncaught (in promise): 3
```

#### AWAIT

因为异步函数主要针对不会马上完成的任务，所以自然需要一种暂停和恢复执行的能力。使用 await 关键字可以暂停异步函数代码的执行，等待期约解决。

```js
let p = new Promise((resolve, reject) => setTimeout(resolve, 1000, 3));
p.then((x) => console.log(x)); // 3
```

使用 async/await 可以写成这样：

```js
async function foo() {
  let p = new Promise((resolve, reject) => setTimeout(resolve, 1000, 3));
  console.log(await p);
}
foo();
// 3
```

await 关键字会**暂停执行异步函数后面的代码，让出 JS 运行时的执行线程**。这生成器函数中的 yield 关键字一样。await 关键字同样是尝试“解包”对象的值，然后将这个值传给表达式，再异步恢复异步函数的执行。用法与 JS 的一元操作一样。它可以单独使用，也可以在表达式中使用

```js
async function baz() {
  await new Promise((resolve, reject) => setTimeout(resolve, 1000));
  console.log("baz");
}
baz();
// baz（1000 毫秒后）
```
